// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtx4wm9tin7ZaiTQo2HiWoM73ccgpL7Hs',
    appId: '1:39328925634:android:ad68727b697a0fbbb4f85b',
    messagingSenderId: '39328925634',
    projectId: 'spotify-clone-4b54a',
    storageBucket: 'spotify-clone-4b54a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYzmTaQBuGQZ2NPaHR5QImSmyErWLE0E',
    appId: '1:39328925634:ios:3115a4c67bba149cb4f85b',
    messagingSenderId: '39328925634',
    projectId: 'spotify-clone-4b54a',
    storageBucket: 'spotify-clone-4b54a.firebasestorage.app',
    iosBundleId: 'com.example.spotifyClone',
  );
}
/*

Platform  Firebase App Id
android   1:39328925634:android:ad68727b697a0fbbb4f85b
ios       1:39328925634:ios:3115a4c67bba149cb4f85b

*/